apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-productos
  labels:
    app: servicio-productos
spec:
  replicas: 1
  template:
    metadata:
      name: servicio-productos
      labels:
        app: servicio-productos
    spec:
      containers:
        - name: servicio-productos
          image: georgegxx/servicio-productos:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always