apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-usuarios
  labels:
    app: servicio-usuarios
spec:
  replicas: 1
  template:
    metadata:
      name: servicio-usuarios
      labels:
        app: servicio-usuarios
    spec:
      containers:
        - name: servicio-usuarios
          image: georgegxx/servicio-usuarios:latest
          imagePullPolicy: Always
          env:
              - name: SPRING_PROFILES_ACTIVE
                value: kube
      restartPolicy: Always