server:
  ports:
    - 8002
    - 8005
    - 8007
spring:
  application:
    name: servicio-items
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: "*"