server:
  port: ${PORT:0}
spring:
  application:
    name: servicio-productos
    config:
      import: configserver:http://config-server:8888
    cloud:
      config:
        fail-fast: true
  sleuth:
    sampler:
      probability: 1.0
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#logging:
#  file:
#    path: /app/logs/servicio-productos.log