apiVersion: v1
kind: Service
metadata:
  name: servicio-items
spec:
  selector:
    app: servicio-items
  ports:
    - port: 80
      targetPort: 8002
    - port: 80
      targetPort: 8005
    - port: 80
      targetPort: 8007
  type: LoadBalancer